version: '3.4'
name: ApiProdutorRuralCadastro
services:
  produtorruralcadastro.api:
    image: ${DOCKER_REGISTRY-}produtorruralcadastroapi
    container_name: ApiProdutorRuralCadastro
    build:
      context: .
      dockerfile: src/ProdutorRuralCadastro.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "7000:80"
    networks:
      - postech-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  postech-network:
    external: true